Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          TechDivision.Jobs.GoogleApi:
            - 'NodeTypes/*'
            - 'BackendModule'
            -
    modules:
      'administration':
        submodules:
          'google-job-api':
            label: 'TechDivision.Jobs.GoogleApi:BackendModule:title'
            controller: 'TechDivision\Jobs\GoogleApi\Controller\BackendModuleController'
            description: 'TechDivision.Jobs.GoogleApi:BackendModule:description'
            icon: 'icon-briefcase'
    fusion:
      autoInclude:
        TechDivision.Jobs.GoogleApi: true

  Flow:
    log:
      psr3:
        'Neos\Flow\Log\PsrLoggerFactory':
          jobIndexingLogger:
            backend: Neos\Flow\Log\Backend\FileBackend
            backendOptions:
              logFileURL: '%FLOW_PATH_DATA%Logs/JobIndexingLog.log'
              severityThreshold: '%LOG_INFO%'
              createParentDirectories: true
              maximumLogFileSize: 1048576
              logFilesToKeep: 1

TechDivision:
  Jobs:
    GoogleApi:
      options:
        enableApiCallOnJobDeletion: false
        logGoogleClientConfiguration: false

Flowpack:
  GoogleApiClient:
    applicationName: ''
